import '@element-ultra/components/base/style'
import '@element-ultra/theme-chalk/src/pro-table.scss'

import '@element-ultra/components/table/style'
import '@element-ultra/components/data-table/style'
import '@element-ultra/components/pagination/style'
import '@element-ultra/components/button/style'
import '@element-ultra/components/loading/style'
import '@element-ultra/components/dropdown/style'
import '@element-ultra/components/scrollbar/style'
import '@element-ultra/components/input-number/style'
import '@element-ultra/components/select/style'
import '@element-ultra/components/checkbox/style'
import '@element-ultra/components/radio-button/style'
