// For this project development

// GlobalComponents for Volar
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('../packages/element-pro')['ElAffix']
    ElAlert: typeof import('../packages/element-pro')['ElAlert']
    ElAside: typeof import('../packages/element-pro')['ElAside']
    ElAutocomplete: typeof import('../packages/element-pro')['ElAutocomplete']
    ElAvatar: typeof import('../packages/element-pro')['ElAvatar']
    ElBacktop: typeof import('../packages/element-pro')['ElBacktop']
    ElBadge: typeof import('../packages/element-pro')['ElBadge']
    ElBreadcrumb: typeof import('../packages/element-pro')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('../packages/element-pro')['ElBreadcrumbItem']
    ElButton: typeof import('../packages/element-pro')['ElButton']
    ElButtonGroup: typeof import('../packages/element-pro')['ElButtonGroup']
    ElCalendar: typeof import('../packages/element-pro')['ElCalendar']
    ElCard: typeof import('../packages/element-pro')['ElCard']
    ElCarousel: typeof import('../packages/element-pro')['ElCarousel']
    ElCarouselItem: typeof import('../packages/element-pro')['ElCarouselItem']
    ElCascader: typeof import('../packages/element-pro')['ElCascader']
    ElCascaderPanel: typeof import('../packages/element-pro')['ElCascaderPanel']
    ElCheckbox: typeof import('../packages/element-pro')['ElCheckbox']
    ElCheckboxButton: typeof import('../packages/element-pro')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('../packages/element-pro')['ElCheckboxGroup']
    ElCol: typeof import('../packages/element-pro')['ElCol']
    ElCollapse: typeof import('../packages/element-pro')['ElCollapse']
    ElCollapseItem: typeof import('../packages/element-pro')['ElCollapseItem']
    ElCollapseTransition: typeof import('../packages/element-pro')['ElCollapseTransition']
    ElColorPicker: typeof import('../packages/element-pro')['ElColorPicker']
    ElContainer: typeof import('../packages/element-pro')['ElContainer']
    ElConfigProvider: typeof import('../packages/element-pro')['ElConfigProvider']
    ElDataTable: typeof import('../packages/element-pro')['ElDataTable']
    ElDatePicker: typeof import('../packages/element-pro')['ElDatePicker']
    ElDialog: typeof import('../packages/element-pro')['ElDialog']
    ElDivider: typeof import('../packages/element-pro')['ElDivider']
    ElDrawer: typeof import('../packages/element-pro')['ElDrawer']
    ElDropdown: typeof import('../packages/element-pro')['ElDropdown']
    ElDropdownItem: typeof import('../packages/element-pro')['ElDropdownItem']
    ElDropdownMenu: typeof import('../packages/element-pro')['ElDropdownMenu']
    ElEmpty: typeof import('../packages/element-pro')['ElEmpty']
    ElFooter: typeof import('../packages/element-pro')['ElFooter']
    ElForm: typeof import('../packages/element-pro')['ElForm']
    ElFormItem: typeof import('../packages/element-pro')['ElFormItem']
    ElHeader: typeof import('../packages/element-pro')['ElHeader']
    ElIcon: typeof import('../packages/element-pro')['ElIcon']
    ElImage: typeof import('../packages/element-pro')['ElImage']
    ElImageViewer: typeof import('../packages/element-pro')['ElImageViewer']
    ElInput: typeof import('../packages/element-pro')['ElInput']
    ElInputNumber: typeof import('../packages/element-pro')['ElInputNumber']
    ElLink: typeof import('../packages/element-pro')['ElLink']
    ElMain: typeof import('../packages/element-pro')['ElMain']
    ElMenu: typeof import('../packages/element-pro')['ElMenu']
    ElMenuItem: typeof import('../packages/element-pro')['ElMenuItem']
    ElMenuItemGroup: typeof import('../packages/element-pro')['ElMenuItemGroup']
    ElOption: typeof import('../packages/element-pro')['ElOption']
    ElOptionGroup: typeof import('../packages/element-pro')['ElOptionGroup']
    ElPageHeader: typeof import('../packages/element-pro')['ElPageHeader']
    ElPagination: typeof import('../packages/element-pro')['ElPagination']
    ElPopconfirm: typeof import('../packages/element-pro')['ElPopconfirm']
    ElPopper: typeof import('../packages/element-pro')['ElPopper']
    ElProgress: typeof import('../packages/element-pro')['ElProgress']
    ElRadio: typeof import('../packages/element-pro')['ElRadio']
    ElRadioButton: typeof import('../packages/element-pro')['ElRadioButton']
    ElRadioGroup: typeof import('../packages/element-pro')['ElRadioGroup']
    ElRate: typeof import('../packages/element-pro')['ElRate']
    ElRow: typeof import('../packages/element-pro')['ElRow']
    ElScrollbar: typeof import('../packages/element-pro')['ElScrollbar']
    ElSelect: typeof import('../packages/element-pro')['ElSelect']
    ElSlider: typeof import('../packages/element-pro')['ElSlider']
    ElStep: typeof import('../packages/element-pro')['ElStep']
    ElSteps: typeof import('../packages/element-pro')['ElSteps']
    ElSubMenu: typeof import('../packages/element-pro')['ElSubMenu']
    ElSwitch: typeof import('../packages/element-pro')['ElSwitch']
    ElTabPane: typeof import('../packages/element-pro')['ElTabPane']
    ElTable: typeof import('../packages/element-pro')['ElTable']
    ElTableColumn: typeof import('../packages/element-pro')['ElTableColumn']
    ElTabs: typeof import('../packages/element-pro')['ElTabs']
    ElTag: typeof import('../packages/element-pro')['ElTag']
    ElTimePicker: typeof import('../packages/element-pro')['ElTimePicker']
    ElTimeSelect: typeof import('../packages/element-pro')['ElTimeSelect']
    ElTimeline: typeof import('../packages/element-pro')['ElTimeline']
    ElTimelineItem: typeof import('../packages/element-pro')['ElTimelineItem']
    ElTooltip: typeof import('../packages/element-pro')['ElTooltip']
    ElTransfer: typeof import('../packages/element-pro')['ElTransfer']
    ElTree: typeof import('../packages/element-pro')['ElTree']
    ElTreeV2: typeof import('../packages/element-pro')['ElTreeV2']
    ElUpload: typeof import('../packages/element-pro')['ElUpload']
    ElSpace: typeof import('../packages/element-pro')['ElSpace']
    ElSkeleton: typeof import('../packages/element-pro')['ElSkeleton']
    ElSkeletonItem: typeof import('../packages/element-pro')['ElSkeletonItem']
    ElCheckTag: typeof import('../packages/element-pro')['ElCheckTag']
    ElDescriptions: typeof import('../packages/element-pro')['ElDescriptions']
    ElDescriptionsItem: typeof import('../packages/element-pro')['ElDescriptionsItem']
    ElResult: typeof import('../packages/element-pro')['ElResult']
    ElSelectV2: typeof import('../packages/element-pro')['ElSelectV2']
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $message: typeof import('../packages/element-pro')['ElMessage']
    $notify: typeof import('../packages/element-pro')['ElNotification']
    $msgbox: typeof import('../packages/element-pro')['ElMessageBox']
    $messageBox: typeof import('../packages/element-pro')['ElMessageBox']
    $alert: typeof import('../packages/element-pro')['ElMessageBox']['alert']
    $confirm: typeof import('../packages/element-pro')['ElMessageBox']['confirm']
    $prompt: typeof import('../packages/element-pro')['ElMessageBox']['prompt']
    $loading: typeof import('../packages/element-pro')['ElLoadingService']
  }
}

export {}
