import '@element-ultra/components/base/style/css'
import '@element-ultra/components/icon/style/css'
import '@element-ultra/components/checkbox/style/css'
import '@element-ultra/components/radio/style/css'
import '@element-ultra/components/dialog/style/css'
import '@element-ultra/components/button/style/css'
import '@element-ultra/components/pagination/style/css'
import '@element-ultra/components/loading/style/css'

import '@element-ultra/theme-chalk/table-select.css'