import 'components/base/style'
import 'components/icon/style'
import 'components/checkbox/style'
import 'components/radio/style'
import 'components/dialog/style'
import 'components/button/style'
import 'components/pagination/style'
import 'components/loading/style'
import 'components/table/style'
import 'components/popconfirm/style'

import 'theme-chalk/src/table-select.scss'
