import '@element-pro/components/base/style/css'
import '@element-pro/theme-chalk/el-table.css'
import '@element-pro/components/checkbox/style/css'
import '@element-pro/components/tag/style/css'
import '@element-pro/components/tooltip/style/css'
import '@element-pro/components/scrollbar/style/css'
