import '@element-pro/components/base/style'
import '@element-pro/theme-chalk/src/table.scss'
import '@element-pro/components/checkbox/style/index'
import '@element-pro/components/tag/style/index'
import '@element-pro/components/tooltip/style/index'
import '@element-pro/components/scrollbar/style/index'
