// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiFileCopy2Line: typeof import('~icons/ri/file-copy2-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiPlayCircleLine: typeof import('~icons/ri/play-circle-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
