import 'components/base/style'
import 'components/tooltip/style'
// import 'components/button/style'
import 'components/scrollbar/style'
import 'components/form/style'
import 'components/icon/style'
import 'components/form-dialog/style'
import 'components/table/style'

import 'theme-chalk/src/multiple-form.scss'
